# Don't use. Not ready yet
- name: Deploy code to AWS
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure security group exists
      ec2_group:
        name: atai
        description: atai
        region: us-east-1
        rules:
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0

    - name: Create deploy instance
      ec2:
        count_tag:
          Name: atai
        exact_count: 1
        group: atai
        image: ami-37bb714d
        instance_tags:
          Name: atai
        instance_type: t2.micro
        keypair: man
        region: us-east-1
        wait: yes
      register: ec2

    - set_fact:
        public_ip: "{{ ec2.tagged_instances[0].public_ip }}"
        instance_ids: "{{ ec2.tagged_instances | map(attribute='id') | list }}"

    - name: Add instance to inventory
      add_host:
        name: atai
        ansible_ssh_host: "{{ public_ip }}"
        ansible_ssh_user: ubuntu

    - name: Wait for instance to come up
      wait_for:
        host: "{{ public_ip }}"
        port: 22
        timeout: 60

    - name: Upload code
      shell: |
        rsync --verbose --stats --progress --delay-updates -F --compress --archive \
        --include='*.py' --include='Pipfile*' --exclude='*' \
        --out-format='<<CHANGED>>%i %n%L' . \
        ubuntu@{{ public_ip }}:/home/ubuntu/atai

    - delegate_to: atai
      block:
      - name: Install pipenv
        pip:
          name: pipenv
          executable: /usr/local/bin/pip
          extra_args: --user

      - name: Install dependencies
        shell: bash -lc "pipenv install --three --ignore-pipfile" chdir=~/atai

      - name: Train model
        shell: bash -lc "pipenv run python train.py notmnist_small.npz" chdir=~/atai

#    - name: Tear down deploy instance
#      ec2:
#        instance_ids: "{{ instance_ids }}"
#        region: us-east-1
#        state: absent
#        wait: yes
